query TourDetail($id: String) {
  tour(where: {slug: $id}) {
    title
    subtitle
    headerImage {
      url
      height
      width
    }
    image {
      url
      height
      width
    }
    description {
      markdown
    }
    price {
      isPromotion
      price
      quantity
      stage
      amountName
    }
    destination {
      ... on Destination {
        title
        subtitle
        shortDescription
        slug
        price {
          isPromotion
          price
          quantity
          stage
          amountName
        }
        headerImage {
          url
          height
          width
        }
      }
    }
    product {
      ... on Product {
        title
        subtitle
        shortDescription
        slug
        price {
          isPromotion
          price
          quantity
          stage
          amountName
        }
        headerImage {
          url
          height
          width
        }
      }
    }
    shop {
      instagramLink
      shopName
      waNumber
      slug
      shopLogo {
        url
        width
        height
      }
      gmapsLink
      shortDescription
    }
  }
}