query Products {
	products {
		title
        subtitle
		shortDescription
		slug
		isVisible
        price {
			isPromotion
			price
			quantity
			stage
			amountName
		}
		headerImage {
			url
			height
			width
		}
    }
}
