query Products {
	products {
		title
        subtitle
		shortDescription
		slug
        price {
			isPromotion
			price
			quantity
			stage
			amountName
		}
		headerImage {
			url
			height
			width
		}
    }
}
