query Accommodations {
  accommodations {
    title
    subtitle
    slug
    shortDescription
    otaLink
    price {
			isPromotion
      isAvailable
			price
			quantity
			amountName
		}
    headerImage {
      width
      url
      height
    }
  }
}
