query DestinationDetail($id: String) {
	destination(where: { slug: $id }) {
		id
		image {
			url
			width
			height
		}
		isFeatured
		location {
			latitude
			longitude
			
		}
		price {
			isPromotion
			price
			quantity
			stage
			amountName
		}
		shortDescription
		shortLocation
		slug
		subtitle
		title
		shop {
			instagramLink
			shopName
			waNumber
			slug
			shopLogo {
				url 
				width 
				height
			}
			gmapsLink
			shortDescription
		}
		description {
			markdown
		}
	}
}
