query MapsLocation {
  destinations {
    slug
    title
    shortDescription
    headerImage {
      url
      height
      width
    }
    location {
      latitude
      longitude
    }
  }
  products {
    slug
    title
    subtitle
    shortDescription
    headerImage {
       url
      height
      width
    }
    location {
      latitude
      longitude
    }
  }
}
